name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

#   - name: Install Dependencies
#      run: npm install  # Adjust this line if your project requires a different build process
#
#    - name: Build
#      run: npm run build  # Adjust or remove this line depending on whether your project needs a build step

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

